### PR TITLE
Force push with lease

### PR DESCRIPTION
**Pull request by sschuberth**
To ensure no one else has pushed since we fetched.

### CODE REVIEW

**Comment by sschuberth** [comment]
Like the commit message says, the difference is that the remote is not unconditionally overwritten, but only if its state when pushing still matches the state that was fetched. For more details please see the [official docs](https://git-scm.com/docs/git-push#Documentation/git-push.txt---no-force-with-lease).

**Comment by sschuberth** [comment]
@RDIL , @fkorotkov, is there anything blocking this (and the other PRs) to get merged?

**Comment by fkorotkov** [comment]
@sschuberth thanks for pinging! I totally missed the PRs. My apologies. 😪Reviewing and merging now.

**Comment by sschuberth** [comment]
Thanks!

**Pull request merged**
