### PR TITLE
Fixed bug with USER_LOGIN

### PR DESCRIPTION
**Pull request by jackton1**
**BEFORE**
Screen Shot 2021-05-14 at 7 46 14 PM

**AFTER**
Screen Shot 2021-05-14 at 7 46 43 PM

@fkorotkov @sschuberth @vorburger

### CODE REVIEW

**Review by fkorotkov — APPROVED** [review]

**Comment by jackton1** [comment]
Can we also get a new release @fkorotkov.

Thanks

**Comment by fkorotkov** [comment]
Im AFK. Will do once at home. 😅

**Comment by jackton1** [comment]
🚀 Release me 🚀

**Comment by fkorotkov** [comment]
Just release 1.5. Sorry for the delay!

**Pull request merged**
